//
//  SessionInitialize.swift
//  StreamOneSDK
//
//  Created by Nicky Gerritsen on 16-08-15.
//  Copyright © 2015 StreamOne. All rights reserved.
//

import Foundation
import Argo
import Curry

/**
    Type as returned by the `session/initialize` API action
*/
public struct SessionInitialize : Decodable {
    /**
        The challenge generated by the server, to be used for generating a response
    */
    public let challenge: String

    /**
        The salt for the user, to be used for generating a response. Will contain a fake salt when the user can not be found
    */
    public let salt: String

    /**
        When true, we require the API version 2 password hash to create the session
    */
    public let needsV2Hash: Bool

    /**
        Decode a JSON object into a session/initialize response

        - Parameter json: The JSON to decode
        - Returns: The decoded session/initialize response
    */
    public static func decode(json: JSON) -> Decoded<SessionInitialize> {
        return curry(SessionInitialize.init)
            <^> json <| "challenge"
            <*> json <| "salt"
            <*> json <| "needsv2hash"
    }
}